### ISSUE TITLE
Send picture from Discord to IRC

### ISSUE THREAD

**Issue by milandamen** [milandamen/Discord-IRC-Python#1]
Make the bot send the link to the uploaded picture (cdn.discordapp.com/..)

**Comment by redtide** [comment]
Replacing [irc.send_my_message] line with something like
```py
    content = message.content
    if len(message.attachments) > 0:
        content += ' ' + message.attachments[0].url

    irc.send_my_message("%s: %s" % (message.author.name, content))
```
seems to work with any file type.

[irc.send_my_message]: https://github.com/milandamen/Discord-IRC-Python/blob/master/discordc.py#L80

**Comment by milandamen** [comment]
Looks pretty good! If it works, please make a pull request.
