### ISSUE TITLE
Decode channel and user name when sending to IRC

### ISSUE THREAD

**Issue by milandamen** [milandamen/Discord-IRC-Python#2]
Instead of sending `<#123451234512345123>` send the real name.

**Comment by iammanish17** [comment]
@milandamen I have fixed the issue in my forked version. But in case of usernames, it only works if the name of the person is not changed in the server.

**Comment by milandamen** [comment]
@iammanish17 nice work on the fork! Sadly, I don't really maintain this repository any more because I don't use the bot any more.

I also saw that you changed the way the user configures their settings; I was wondering if you were aware that if a user changes their `settings.json` they will likely get merge conflicts if they pull a newer version of the settings file. That's the reason I had the `settings.example.json` instruction, even though that also isn't optimal because it breaks when other mandatory settings get added. What's your opinion on this?

**Comment by iammanish17** [comment]
@milandamen I have no problem with adding the settings.example.json instruction, but that's not really necessary.
